### ISSUE TITLE
Dual target .net-3.5 and .net-4.0

### ISSUE THREAD

**Issue by binki** [joelpurra/xmouse-controls#11]
On a fresh Windows 10 install, trying to run xmouse-controls shows this:

![image](https://user-images.githubusercontent.com/82626/45509630-229c0e80-b766-11e8-8f71-de70b8bb6b76.png)

It is possible to build the utility in such a way that Windows is willing to use .net-4.0 to run it: https://stackoverflow.com/a/20865375 . Since this is a simple utility, it would be nice if it listed both SKUs so that it would just work out of the box everywhere without requiring installation of .net-3.5.

I tested the `app.config` method and it works as long as you have the `.config` file next to the executable. I will make a PR soon and may investigate if I can do this with the embedded manifest somehow instead of only in the external `.config` file.

**Comment by joelpurra** [comment]
@binki: thanks for looking into this! Long gone is the dream of no version problems in .net ;)

**Comment by binki** [comment]
Thanks for merging this and building the beta ZIP! I don’t do it happen often, but this really does make configuring a freshly installed Windows 10 VM or machine (which doesn’t have .net-3.5) much easier.
