### ISSUE TITLE
This is not an issue...

### ISSUE THREAD

**Issue by OgierM** [joelpurra/xmouse-controls#15]
...but more of an interesting observation. The behaviour is being synched between Windows 10 machines if you are logged in with your Microsoft account.

**Comment by joelpurra** [comment]
Wow, cool! Am not logged in using a Microsoft account, so haven't noticed. One of the benefits of using official (but "hidden") Windows settings, I guess. Hopefully X-Mouse Controls' users find this beneficial!

Closing the "issue". Thank you for letting us know =)
