### ISSUE TITLE
Web site download link is for debug build

### ISSUE THREAD

**Issue by M-a-r-k** [joelpurra/xmouse-controls#16]
On the X-Mouse Controls web site, the "Download latest version" button links to https://files.joelpurra.com/projects/x-mouse-controls/2018-10-06T1730Z/x-mouse_controls_2018-10-06T1730Z_debug.zip

(You can download the release build by scrolling down the page and clicking the v1.1.0.0 download link.)

**Comment by joelpurra** [comment]
@M-a-r-k: yeah, you're right. Doesn't make much of a difference, technically, but looks better this way. Fixed, thanks!
