### ISSUE TITLE
Wish: disable raise-on-click

### ISSUE THREAD

**Issue by GrantEdwards** [joelpurra/xmouse-controls#19]
Would it be possible to add an option to disable the raising of a window by a mouse click inside window?

On X, I've always been able to click on controls inside a window without raising it.  IOW, raise only when clicking the window banner/border.

[Even without disabling raise-on-click, I think I could have justified using my HSA Visa card instead of my "normal" one to make a donation — because windows default behavior was going to kill me.]

**Comment by joelpurra** [comment]
@GrantEdwards: no, as far as I know click-raising can't be disabled. The responsibility to raise the window seems to belong to each program, although it might be builtin to some oft-used or standard user interface components/controls. Depending on which programs you use, you might be able to find certain workarounds -- but don't expect them to be consistent.

You can test one window raising workaround (at least on Windows 10) by piling some partially overlapping applications, one of which is a regular File Explorer window. With other windows on top, you can still click (left, right, even double-click) listed items such as folders and drives (both in the tree pane and item pane) without raising the window. The window will raise if you click for example a scrollbar, or an empty space between items though.

You can see how-fine grained the behavior is if you click a File Explorer menu item (such as _home_ or _share_) in the top bar. By default it drops down an expanded menu bar and raises the window, but it won't raise if you have first pinned the expanded menu bar by clicking the small 📌 in the top right corner. Pinning the expanded menu bar does not work for the _file_ menu though, as it always shows a dropdown menu. So the the raising behavior might not only belong to the component which receives the click, but also the effect of the click -- in this case the dropdown menu component seems to control window focus and raising.

Sorry, can't grant your wish. I'll close this issue as I don't see it being fixable within the scope of X-Mouse Controls, but feel free to post follow-up comments.

---

Had to look up HSA, and am guessing it means _health savings account_. Haha, would be funny if Windows' window handling would be considered a health issue. Will keep it in mind for Talkie, which is an accessibility tool. Thank you for supporting open source software, much appreciated =)

- https://en.wikipedia.org/wiki/HSA#Other_uses
- https://github.com/joelpurra/talkie
