### ISSUE TITLE
Allow app window to have focus for specific apps only

### ISSUE THREAD

**Issue by jedis00** [joelpurra/xmouse-controls#28]
Hello,

I would like a particular app to have focus when my mouse moves over it, however I only want it to work for a specific application.

Is this possible as a feature enhancement?

Thank you!

**Comment by joelpurra** [comment]
@jedis00: sorry, it's not possible with X-Mouse Controls.

See for example what @binki wrote in https://github.com/joelpurra/xmouse-controls/issues/27#issuecomment-1077278272:

> The Windows settings which are tweaked are general and cover everything. There is no way to restrict it to specific windows that I know of. I suspect that Windows does not support this.

Closing this issue as out of scope for X-Mouse Controls.
