### ISSUE TITLE
Are there any keyboard shortcuts to enable/disable it?

### ISSUE THREAD

**Issue by dpw1** [joelpurra/xmouse-controls#29]
Hi, 

First of all, thanks for the great software!

Are there any keyboard shortcuts to enable/disable mouse active window tracking?

**Comment by joelpurra** [comment]
@dpw1: sorry, there are no keyboard shortcuts, and no plans to add them.

X-Mouse Controls is implemented to be a run-once set-and-forget program, not an application sitting idle in the background. Also, (global) keyboard shortcuts need to be user configurable, which requires additional user-interface controls/system hooks/error checking/etcetera, and it's no something I'd personally like to focus on.

- https://en.wiktionary.org/wiki/set-and-forget
- https://github.com/joelpurra/xmouse-controls/issues/7

As an alternative, it's also possible to script the equivalent functionality using PowerShell and bind a keyboard shortcut to the script. If you do this, it'd be appreciated if you share/link those scripts in this issue =)

- https://github.com/joelpurra/xmouse-controls/issues/22
- https://stackoverflow.com/questions/39677467/launch-powershell-script-with-keyboard-hotkey

While some applications do not be have well with active window tracking enabled, there are common workaround and strategies covering nearly all cases. You'll find some basic tips on the website, and a bunch more in the issues here on github.

- https://joelpurra.com/projects/X-Mouse_Controls/#usage
- https://github.com/joelpurra/xmouse-controls/issues?q=

Closing the issue as wontfix, but please ask follow-up questions if you have them. Thanks for using X-Mouse Controls, happy that you like it =)
