### ISSUE TITLE
Please release xmouse-controls as a plain old Zip file

### ISSUE THREAD

**Issue by unforgettableid** [joelpurra/xmouse-controls#3]
It would be great if you could please release xmouse-controls as a plain old Zip file.  That way, users wouldn't need to install a .7z archive extraction utility in order to run it.

I'm on broadband Internet, so I'm unconcerned about the size of the download.

P.S.  Thank you very much for writing and open-sourcing xmouse-controls!  It works as promised.

**Comment by joelpurra** [comment]
@unforgettableid wrote:
> It would be great if you could please release xmouse-controls as a plain old Zip file. That way, users wouldn't need to install a .7z archive extraction utility in order to run it.

I understand your concern. It's by choice though -- I want people to install 7z software. Nowadays Windows can unpack .zip files out of the box so Winzip/Winrar/etcetera isn't required anymore. This is just my way of promoting 7z, which is my personal preference when it comes to compression utilities. (Also using [xz](https://en.wikipedia.org/wiki/Xz) on non-windows boxes.)

> I'm on broadband Internet, so I'm unconcerned about the size of the download.

I'm currently on a very slow connection which drops quite often, and do care about download sizes.

> P.S. Thank you very much for writing and open-sourcing xmouse-controls! It works as promised.

Glad to hear! I'll keep your suggestion in mind =)

**Comment by roobie** [comment]
+1. I wish more people used 7z.

**Comment by joelpurra** [comment]
@unforgettableid, @samhasler: should note that I've finally (since January 2017) uploaded zip files.

@roobie: while the 7z files are still there, the links have now been commented out; wanted to reduce the number of links un the UI. Still on the side of lzma2, but after a few years less happy about the xz "fork" of 7z.
