### ISSUE TITLE
impossible to scroll

### ISSUE THREAD

**Issue by 1C0D** [joelpurra/xmouse-controls#30]
under firefox scroll is impossible (recently) unless you turn on scroll lock (I'm under azerty keyboard)
so you can't use it anymore...

**Comment by 1C0D** [comment]
ok solved with the update

**Comment by binki** [comment]
@1C0D how does this relate to this project? Can you describe more in detail what you are doing? Do you mean using the middle wheel of the mouse to scroll? Are you talking about a particular webpage?

**Comment by 1C0D** [comment]
@binki it has been solved by the last update

**Comment by binki** [comment]
@1C0D the latest update of what? ;-)

**Comment by 1C0D** [comment]
@binki haha I think it was not the good repo indeed. X mouse button control.
