### ISSUE TITLE
Add minimize button

### ISSUE THREAD

**Issue by bitofhope** [joelpurra/xmouse-controls#5]
Requesting to have minimize button on the window. I use xmouse-controls on a shared computer account on a slow computer and reopening the program in order to change back to normal settings for the next user takes quite some time.

**Comment by joelpurra** [comment]
Not a bad idea! I also see that there is a pull request for this feature in #6; will comment on it there and keep this issue open.

**Comment by Zurd** [comment]
FYI, I've achieved what I needed with a simple Powershell script:
https://superuser.com/questions/954021/how-do-you-enable-focus-follows-mouse-in-windows-10#answer-1209478

**Comment by Zurd** [comment]
Forget about the Powershell script, it mess up the Start menu and the Cortana search.

I've tried instead the first post of the user in the link I posted, Ease of Access Center + registry hack and I have no issue with it.

**Comment by joelpurra** [comment]
@bitofhope: thank you for the suggestion! It was implemented by @binki, many thanks!

I've just uploaded X-Mouse Controls v1.1.0.0. It's listed as "beta" at the top, but also listed in the downloads section. Does minimizing work properly for you guys?

https://joelpurra.com/projects/X-Mouse_Controls/

**Comment by joelpurra** [comment]
@Zurd: finally added the minimize button! Download the "beta" X-Mouse Controls v1.1.0.0 and let me know what you think! As the program doesn't have to run all the time (only when you want to make a settings change) I'm not sure I'll add minimizing to the system tray -- especially if RBTray works well.

https://joelpurra.com/projects/X-Mouse_Controls/

**Comment by bitofhope** [comment]
Cheers, works like a charm!

**Comment by Zurd** [comment]
Wonderful, thank you for this new feature!

Forget about the new solution I have found with "Ease of Access Center + registry hack", it didn't work well in the end. However, X-Mouse Controls isn't perfect either, the Cortana search will not work with the setting of window tracking checked at 0ms. But you can still use Cortana by using only the keyboard, which is faster than the mouse (for example, click Cortana, make a search, use the arrows on the keyboard and press Enter).

To make it work with RBTray to minimize X-Mouse Controls and have it into the system tray:
```
 - Copy RBHook.dll to C:\Windows\System32
 - Copy RBTray.exe, X-Mouse Controls.exe to C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp
 - Reboot
 - At startup, just right-click the minimize button in X-Mouse Controls
```

**Comment by Zurd** [comment]
Actually, I didn't know that if you close X-Mouse Controls with the X button, that it will still run in the background. It's even better that way. No need for RBTray, as you said, you don't need to modify the settings often, at worst, just reboot and you will be able to.

So installation is even easier, just copy "X-Mouse Controls.exe" to C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp and reboot.

**Comment by binki** [comment]
> Actually, I didn't know that if you close X-Mouse Controls with the X button, that it will still run in the background.

X-Mouse Controls doesn’t run in the background. It is a utility which you run once and [uses API calls to edit the registry on your behalf](https://github.com/joelpurra/xmouse-controls/blob/1470bc92cc0344cbc4efd60a2901f10657fef7c0/docs/index.html#L124). The actual implementation is in Windows itself—X-Mouse Controls doesn’t hook into anything or try to raise windows itself.

I’m not sure this is very explicitly documented. The closest I can find is under the “Apply” section of the project page: https://github.com/joelpurra/xmouse-controls/blob/1470bc92cc0344cbc4efd60a2901f10657fef7c0/docs/index.html#L124

> Saves the settings and applies them to your system. The settings come in effect right away, and stay even after rebooting.

But it doesn’t say that the settings don’t need the program to run. Maybe that should be added to the project page?

**Comment by Zurd** [comment]
Thank you for the clarification binki. Indeed, you do not even need to run the program. Just double-click X-Mouse, set your configuration and close it. The changes will stay after reboot, no need for the Startup program. This is actually even better and less complicated.

So there was no need for a minimize button in the first place ;)

**Comment by joelpurra** [comment]
@Zurd: yeah, the minimize button is more for those who turn on/off the feature very often. Some have that use case, be it a shared (perhaps family) computer or some programs which are very hard to use with X-Mouse enabled.

**Comment by joelpurra** [comment]
@binki: there's at least one more mention on the project page. There is also a mention in the (beta) program, once the information pane has been extended.

Unsure how common the misconception that the program has to run all the time, on every boot -- have no numbers on actual usage, and do not intend to collect any. Is more information needed?

Project page:

https://joelpurra.com/projects/X-Mouse_Controls/#usage

https://github.com/joelpurra/xmouse-controls/blob/1470bc92cc0344cbc4efd60a2901f10657fef7c0/docs/index.html#L136

Information pane (beta):

https://github.com/joelpurra/xmouse-controls/blob/develop/X-Mouse%20Controls/MainWindow.xaml#L106

**Comment by Zurd** [comment]
And again, I stopped using XMouse, the problematic behavior of Cortana and the notification area (bottom right completely) is just too annoying. The save window of GIMP too, you must ctrl-tab and use the keyboard only. In the end, only Linux implement window raising correctly, there is no way to do the same in Windows.
